# Generated by Django 5.1.3 on 2024-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="is_from_host",
            field=models.BooleanField(default=False),
        ),
    ]
